### ISSUE TITLE
Dense_Block

### ISSUE THREAD

**Issue by jaywong003** [luanshiyinyang/DenseNet#1]
Dense_Block 中的
        cb = Conv_Block(x, growth_rate, bottleneck, dropout_rate, weight_decay)
是不是应该改为：
        cb = Conv_Block(x, filters, bottleneck, dropout_rate, weight_decay)
？

**Comment by luanshiyinyang** [comment]
yes, you are right. I have fixed this bug and commit a new version. This issue will cbe closed.
